version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/var/lib/mongodb/data

  redis-cache:
    container_name: redis-cache
    image: redis:7.2.3-alpine
    restart: always

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - mongodb
      - redis-cache

  client:
    container_name: client
    build:
      context: ./client
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - server

volumes:
  mongodb-data: