version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 4000:4000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - server

  mongo:
    container_name: mongo
    image: mongo:7.0
    restart: always
    volumes:
      - mongodb-data:/var/lib/mongodb/data
    networks:
      - express-mongo
    expose:
      - 27017

  server:
    container_name: server
    build:
      context: server
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - express-mongo
      - react-express
    depends_on:
      - mongodb

networks:
  react-express:
  express:mongo:

volumes:
  mongodb-data: