const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

const SIGNUP_REQUEST = "SIGNUP_REQUEST";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_FAILURE = "SIGNUP_FAILURE";

const GET_USER_REQUEST = "GET_USER_REQUEST"
const GET_USER_SUCCESS = "GET_USER_SUCCESS"
const GET_USER_FAILURE = "GET_USER_FAILURE"

const USER_LOGOUT = "USER_LOGOUT"

export { 
    LOGIN_REQUEST, 
    LOGIN_SUCCESS, 
    LOGIN_FAILURE,
    SIGNUP_REQUEST,
    SIGNUP_SUCCESS,
    SIGNUP_FAILURE,
    USER_LOGOUT,
    GET_USER_REQUEST,
    GET_USER_SUCCESS,
    GET_USER_FAILURE 
}